name: DodoTest
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  RunTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          set -ex
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo apt install ./google-chrome-stable_current_amd64.deb
          python -m pip install --upgrade pip
          pip install pytest PyYAML selenium allure-pytest msedge-selenium-tools
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Install allure
        run: |
          wget https://github.com/allure-framework/allure2/releases/download/2.17.3/allure_2.17.3-1_all.deb
          sudo apt install ./allure_2.17.3-1_all.deb
      - name: Run test 
        run: python run.py
